FROM jetbrains/teamcity-agent:2017.2.3-windowsservercore

# SHELL ["powershell"]
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

RUN ./dotnet 