//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//This source code was auto-generated by MonoXSD
//
namespace FileFlows.ServerShared.Models.Schemas {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class nvidia_smi_log {
        
        private string timestampField;
        
        private string driver_versionField;
        
        private string cuda_versionField;
        
        private string attached_gpusField;
        
        private nvidia_smi_logGpu[] gpuField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string driver_version {
            get {
                return this.driver_versionField;
            }
            set {
                this.driver_versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cuda_version {
            get {
                return this.cuda_versionField;
            }
            set {
                this.cuda_versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string attached_gpus {
            get {
                return this.attached_gpusField;
            }
            set {
                this.attached_gpusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("gpu", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public nvidia_smi_logGpu[] gpu {
            get {
                return this.gpuField;
            }
            set {
                this.gpuField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class nvidia_smi_logGpu {
        
        private string product_nameField;
        
        private string product_brandField;
        
        private string product_architectureField;
        
        private string serialField;
        
        private string uuidField;
        
        private string minor_numberField;
        
        private string vbios_versionField;
        
        private string multigpu_boardField;
        
        private string board_idField;
        
        private string gpu_part_numberField;
        
        private string gpu_module_idField;
        
        private string fan_speedField;
        
        private string performance_stateField;
        
        private nvidia_smi_logGpuFb_memory_usage[] fb_memory_usageField;
        
        private nvidia_smi_logGpuBar1_memory_usage[] bar1_memory_usageField;
        
        private nvidia_smi_logGpuUtilization[] utilizationField;
        
        private nvidia_smi_logGpuEncoder_stats[] encoder_statsField;
        
        private nvidia_smi_logGpuFbc_stats[] fbc_statsField;
        
        private nvidia_smi_logGpuTemperature[] temperatureField;
        
        private nvidia_smi_logGpuSupported_gpu_target_temp[] supported_gpu_target_tempField;
        
        private nvidia_smi_logGpuPower_readings[] power_readingsField;
        
        private nvidia_smi_logGpuProcessesProcess_info[] processesField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string product_name {
            get {
                return this.product_nameField;
            }
            set {
                this.product_nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string product_brand {
            get {
                return this.product_brandField;
            }
            set {
                this.product_brandField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string product_architecture {
            get {
                return this.product_architectureField;
            }
            set {
                this.product_architectureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string serial {
            get {
                return this.serialField;
            }
            set {
                this.serialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string uuid {
            get {
                return this.uuidField;
            }
            set {
                this.uuidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string minor_number {
            get {
                return this.minor_numberField;
            }
            set {
                this.minor_numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string vbios_version {
            get {
                return this.vbios_versionField;
            }
            set {
                this.vbios_versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string multigpu_board {
            get {
                return this.multigpu_boardField;
            }
            set {
                this.multigpu_boardField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string board_id {
            get {
                return this.board_idField;
            }
            set {
                this.board_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string gpu_part_number {
            get {
                return this.gpu_part_numberField;
            }
            set {
                this.gpu_part_numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string gpu_module_id {
            get {
                return this.gpu_module_idField;
            }
            set {
                this.gpu_module_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fan_speed {
            get {
                return this.fan_speedField;
            }
            set {
                this.fan_speedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string performance_state {
            get {
                return this.performance_stateField;
            }
            set {
                this.performance_stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("fb_memory_usage", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public nvidia_smi_logGpuFb_memory_usage[] fb_memory_usage {
            get {
                return this.fb_memory_usageField;
            }
            set {
                this.fb_memory_usageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("bar1_memory_usage", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public nvidia_smi_logGpuBar1_memory_usage[] bar1_memory_usage {
            get {
                return this.bar1_memory_usageField;
            }
            set {
                this.bar1_memory_usageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("utilization", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public nvidia_smi_logGpuUtilization[] utilization {
            get {
                return this.utilizationField;
            }
            set {
                this.utilizationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("encoder_stats", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public nvidia_smi_logGpuEncoder_stats[] encoder_stats {
            get {
                return this.encoder_statsField;
            }
            set {
                this.encoder_statsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("fbc_stats", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public nvidia_smi_logGpuFbc_stats[] fbc_stats {
            get {
                return this.fbc_statsField;
            }
            set {
                this.fbc_statsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("temperature", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public nvidia_smi_logGpuTemperature[] temperature {
            get {
                return this.temperatureField;
            }
            set {
                this.temperatureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("supported_gpu_target_temp", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public nvidia_smi_logGpuSupported_gpu_target_temp[] supported_gpu_target_temp {
            get {
                return this.supported_gpu_target_tempField;
            }
            set {
                this.supported_gpu_target_tempField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("power_readings", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public nvidia_smi_logGpuPower_readings[] power_readings {
            get {
                return this.power_readingsField;
            }
            set {
                this.power_readingsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("process_info", typeof(nvidia_smi_logGpuProcessesProcess_info), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public nvidia_smi_logGpuProcessesProcess_info[] processes {
            get {
                return this.processesField;
            }
            set {
                this.processesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class nvidia_smi_logGpuFb_memory_usage {
        
        private string totalField;
        
        private string reservedField;
        
        private string usedField;
        
        private string freeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string reserved {
            get {
                return this.reservedField;
            }
            set {
                this.reservedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string used {
            get {
                return this.usedField;
            }
            set {
                this.usedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string free {
            get {
                return this.freeField;
            }
            set {
                this.freeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class nvidia_smi_logGpuBar1_memory_usage {
        
        private string totalField;
        
        private string usedField;
        
        private string freeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string used {
            get {
                return this.usedField;
            }
            set {
                this.usedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string free {
            get {
                return this.freeField;
            }
            set {
                this.freeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class nvidia_smi_logGpuUtilization {
        
        private string gpu_utilField;
        
        private string memory_utilField;
        
        private string encoder_utilField;
        
        private string decoder_utilField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string gpu_util {
            get {
                return this.gpu_utilField;
            }
            set {
                this.gpu_utilField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string memory_util {
            get {
                return this.memory_utilField;
            }
            set {
                this.memory_utilField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string encoder_util {
            get {
                return this.encoder_utilField;
            }
            set {
                this.encoder_utilField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string decoder_util {
            get {
                return this.decoder_utilField;
            }
            set {
                this.decoder_utilField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class nvidia_smi_logGpuEncoder_stats {
        
        private string session_countField;
        
        private string average_fpsField;
        
        private string average_latencyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string session_count {
            get {
                return this.session_countField;
            }
            set {
                this.session_countField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string average_fps {
            get {
                return this.average_fpsField;
            }
            set {
                this.average_fpsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string average_latency {
            get {
                return this.average_latencyField;
            }
            set {
                this.average_latencyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class nvidia_smi_logGpuFbc_stats {
        
        private string session_countField;
        
        private string average_fpsField;
        
        private string average_latencyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string session_count {
            get {
                return this.session_countField;
            }
            set {
                this.session_countField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string average_fps {
            get {
                return this.average_fpsField;
            }
            set {
                this.average_fpsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string average_latency {
            get {
                return this.average_latencyField;
            }
            set {
                this.average_latencyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class nvidia_smi_logGpuTemperature {
        
        private string gpu_tempField;
        
        private string gpu_temp_max_thresholdField;
        
        private string gpu_temp_slow_thresholdField;
        
        private string gpu_temp_max_gpu_thresholdField;
        
        private string gpu_target_temperatureField;
        
        private string memory_tempField;
        
        private string gpu_temp_max_mem_thresholdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string gpu_temp {
            get {
                return this.gpu_tempField;
            }
            set {
                this.gpu_tempField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string gpu_temp_max_threshold {
            get {
                return this.gpu_temp_max_thresholdField;
            }
            set {
                this.gpu_temp_max_thresholdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string gpu_temp_slow_threshold {
            get {
                return this.gpu_temp_slow_thresholdField;
            }
            set {
                this.gpu_temp_slow_thresholdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string gpu_temp_max_gpu_threshold {
            get {
                return this.gpu_temp_max_gpu_thresholdField;
            }
            set {
                this.gpu_temp_max_gpu_thresholdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string gpu_target_temperature {
            get {
                return this.gpu_target_temperatureField;
            }
            set {
                this.gpu_target_temperatureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string memory_temp {
            get {
                return this.memory_tempField;
            }
            set {
                this.memory_tempField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string gpu_temp_max_mem_threshold {
            get {
                return this.gpu_temp_max_mem_thresholdField;
            }
            set {
                this.gpu_temp_max_mem_thresholdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class nvidia_smi_logGpuSupported_gpu_target_temp {
        
        private string gpu_target_temp_minField;
        
        private string gpu_target_temp_maxField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string gpu_target_temp_min {
            get {
                return this.gpu_target_temp_minField;
            }
            set {
                this.gpu_target_temp_minField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string gpu_target_temp_max {
            get {
                return this.gpu_target_temp_maxField;
            }
            set {
                this.gpu_target_temp_maxField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class nvidia_smi_logGpuPower_readings {
        
        private string power_stateField;
        
        private string power_managementField;
        
        private string power_drawField;
        
        private string power_limitField;
        
        private string default_power_limitField;
        
        private string enforced_power_limitField;
        
        private string min_power_limitField;
        
        private string max_power_limitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string power_state {
            get {
                return this.power_stateField;
            }
            set {
                this.power_stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string power_management {
            get {
                return this.power_managementField;
            }
            set {
                this.power_managementField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string power_draw {
            get {
                return this.power_drawField;
            }
            set {
                this.power_drawField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string power_limit {
            get {
                return this.power_limitField;
            }
            set {
                this.power_limitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string default_power_limit {
            get {
                return this.default_power_limitField;
            }
            set {
                this.default_power_limitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string enforced_power_limit {
            get {
                return this.enforced_power_limitField;
            }
            set {
                this.enforced_power_limitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string min_power_limit {
            get {
                return this.min_power_limitField;
            }
            set {
                this.min_power_limitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string max_power_limit {
            get {
                return this.max_power_limitField;
            }
            set {
                this.max_power_limitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class nvidia_smi_logGpuProcessesProcess_info {
        
        private string gpu_instance_idField;
        
        private string compute_instance_idField;
        
        private string pidField;
        
        private string typeField;
        
        private string process_nameField;
        
        private string used_memoryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string gpu_instance_id {
            get {
                return this.gpu_instance_idField;
            }
            set {
                this.gpu_instance_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string compute_instance_id {
            get {
                return this.compute_instance_idField;
            }
            set {
                this.compute_instance_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pid {
            get {
                return this.pidField;
            }
            set {
                this.pidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string process_name {
            get {
                return this.process_nameField;
            }
            set {
                this.process_nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string used_memory {
            get {
                return this.used_memoryField;
            }
            set {
                this.used_memoryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class NewDataSet {
        
        private nvidia_smi_log[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("nvidia_smi_log")]
        public nvidia_smi_log[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
}
